### ISSUE TITLE
关于维护方面的一点思考

### ISSUE THREAD

**Issue by EnixCoda** [tianyilt/ecnu-PGCourseShare#4]
Hi, @tianyilt 

看到这个项目我特别激动，因为以前我也开发、维护过[类似的](https://github.com/EnixCoda/ECNU-SEI-ONEPIECE/)，但规模不大，仅仅在软院内部推了一下，有~200名同学用过，而且现在已经下线。开这个 issue 主要是有一些思考和困难想分享一下，期待这个 repo 能走得更远。

我读了[前言](https://github.com/tianyilt/ecnu-PGCourseShare#%E5%89%8D%E8%A8%80)，发现我们产生做这件事的缘由和初步思考是一致的，区别在于采取的运行方式不同。

### 网盘
网盘是最先想到的形式，我除了同意前言写到的网盘优缺点，我还想特别指出的是网盘缺乏良好的用户反馈机制，文件的“新陈代谢”难以保障。前言里虽然没特地写但你应该也是很清楚的。

### 基于 git 的管理（GitHub）
我也考虑过，没采用是因为
- GitHub 的使用是有些微门槛的，比如 git, GitHub 的基本概念、注册才能通过 issue 反馈和维护、众所周知的网络问题、下载文件不便利
- 虽然可以反馈和维护，但基础机制是 GitHub issue，提交 issue 的时候是较难联系到具体文件的，反过来说查看文件的时候是较难看到它相关的 issue 的，因此使用过程中同学们会因为日益增多的文件而增加获取、选择的成本
- 对于部分 Word、PPT 缺乏预览能力，需要下载查看，而大多数时候同学需要的只是打开阅读
- 需要维护者定期处理 issue ，会有一定的负担

### 我采取的方案
定制化开发网站
- 核心功能是文件浏览和管理
- 同学们不需要特别注册，通过校内数据库账户就可以直接登陆
- 提供 Word、PPT、PDF 等常见文件格式的站内预览，可以满足查阅的需求
- 提供了文件评价的功能，可以在打开文件页面的时候直接看到，除了文字评价还有评分 👍/👎 ，点击一下就行，非常方便，扫去了同学们反馈的门槛。在文件列表可以清楚的知道哪些文件是被同学们推荐的，低评分的文件会自动归入 Archive

关于维护，我的方案是**不需要特定维护者**，每位同学都有权限维护，但个人的权限又不足以直接对文件产生改动。在每个文件的页面，除了刚提到的评价，还可以看到其他同学对这个文件提出的维护提议，比如“重命名该文件为《习题集.pdf》“，认为这个提议可行的同学在旁边点一下 👍/👎 即可为这个提议加减权重，权重达到预设的阈值系统就会自动执行这个维护。维护能被自动执行的前提是维护内容是预设好的操作，对于这样简单的文件管理系统，维护无非是 移动、重命名（本质上也是移动）、删除，所以不复杂，UI上的操作门槛也很低。

但这也不意味着不能有高权限的维护者直接改文件，上述维护方案主要是确保了站点脱离特定维护者也可以持久运转。

## 没能解决的问题
- 找到合适的同学接替的站点开发迭代工作
  我有征求同学帮忙进行开发，主要是解决bug和进行迭代（如果有的话），工作量很小很小。也确实收到过自告奋勇的同学，但只有一位，而且最后没能真正达成合作，因为这个门槛包括掌握网站现有的技术栈，对于本科阶段的同学来说很难，有这精力可能不如去刷点题。
- 为维护者提供合适的奖励机制
  如果被采用的维护能加绩点就好了，整个站一定热热闹闹的……开个玩笑

---
时间久远，目前能想起来的就这么多，希望能启发看到这里的同学产生新的想法。我也不知道这个问题的真正解法在哪里，但看到还有人在努力真的特别高兴 :D

**Comment by tianyilt** [comment]
谢谢学长的分享. 对于共建共享的攻略社区的建设提供新的视角让我很受启发.
项目历史:其实这个项目的真实时间应该是3年,有2年半是以https://github.com/tianyilt/ecust-CourseShare的形式呈现的. 因此我们在实践中同样遇到了 网盘更新延迟 github门槛高 以及 项目存续依赖于少数维护者的问题. 也曾经想要类似中[科大的课程攻略共享计划](https://ustc-resource.github.io/USTC-Course/)那样创建一个网站来方便大家浏览以及更新资料.

网盘更新问题的改进方案: 其实百度云可以设置同步盘,可以解决这个问题, 当然这需要一些钞能力. 进阶版的话, 我在家配了2个NAS,也可以作为同步盘产生文件镜像.

github门槛高的改进方案: 这个门槛其实是
1. 访问困难,由于众所周知的防火墙的问题, github访问速度经常十分低下. 我们发现可以用镜像站来解决,包括在github后面加上1s的vscode查看方式. 用hub.fastgit.org来替代github.com. 从而达到境内快速访问.
2. git 贡献门槛高, 其实访问只要点开readme读一下,然后点击文件夹下载资料就行了,这个没有太高门槛. 而贡献需要git fetch, clone+本地修改+push/在github上传文件, pull request, 确实周期特别长. 比如我在本科的实践中,在有资料的情况下大家还是需要一天来学习的. 好在目前研究生阶段, 而且从计算机科学发起,这个问题不少很大.
学长给出的网站其实我之前一直想做,不过当时我们比较菜(数学系大三,懂的都懂). 就是信息学院的同学肯帮忙,这也是需要很多开发量的,所以我非常佩服这个工作,后面希望可以试验这个网站. 目前实验室服务器资源充足, 可能进一步维护.

项目存续依赖于少数维护者的问题展示想不出解决办法:  这其实涉及到人性问题, 当时本科数学系的情况是16级给17级建立qq群提供资料;17级大受震撼, 专门有一批人长时间进行教学相关内容生产,比如我和几位同学几乎所有课期末都会提供指北攻略,完善QQ群资料库,并且鼓捣一波整了个大新闻,建立这个计划,几位同学社会工作出色,得到国奖(当然本身成绩也很优秀),国奖获得者可以因此发动学院官方宣传,形成闭环;17给18级建立qq群,提供资料,并且和他们说有这个计划,没人参与维护,甚至也没有传下来宝贵的经验.当然这也可能和换届后团委学生会的倾向调整相关.倒是其他学院有人听说,参与进来; 18级给19级建立群, 资料zero, 部分学生愿意加入这个计划,不过确实github门槛比较高,而且17级开始忙了,所以也没太大经历,没有后续更新; 20级据说连群都没建立起来, 专注内卷和黑暗森林. 不过挂科率据说逐渐升高,17级最低,学习氛围也最好.
其实我也希望维护能加绩点,这需要官方的支持. 目前本科的项目只是对评选国奖答辩会有实际加成, 大家国奖都是卷上来的, 甚至内容生产这种事情都未必会做,更别提这种事情了,缺乏经济基础.
我还收到五星社团的维护申请,可能因为当时写论文太咕了,没有继续推进,回头咨询一下.

研究生课程攻略共享计划的目的和本科生存在一定差异. 其实对于课程攻略而言,研究生没有太多需求,及格就行,而且及格这事情还很轻松, 而完成导师的论文或者项目才是最关键的. 所以我觉得这个库肩负的使命应该更加放在推进学术交流那样,有点像上海交大的生存指南.
这方面目前我还在进行内容生产,以及多多认识有意思的同学. 在形成一定基础后尝试破题这个局面.

**Comment by tianyilt** [comment]
再补充一些细节,挂科率25%-50%的模式识别与机器学习(挂科失去学业奖学金6000)目前还没听说有什么迫切的攻略需求. 大家还是按部就班地做作业,我到现在还没有联系到上课同学中有愿意分享1课程资料2复习资料3复习攻略的. 
所以研究生阶段大家可能还是科研为主. 科研为主下大家方向差异非常大,之前国奖大佬答辩,经验分享其实去听的人也寥寥无几. 如何保证共享库提供的资讯能提供真正的普适性的价值也是一个挑战.
但是这样的情况下也有一些好处, 大家交流也未必是出于功利主义. 这个平台更大可能发挥一种社交属性. 这个时候这个共享库的贡献门槛问题又被重新提出来. 这里面的门槛更多指的是大家分享的原因程度. 这是水的源头,非常重要. 目前采取何种方式来保证资讯来源也是一个挑战.

这就涉及到related work了,有心的同学其实往往已经在b站 知乎 youtube 各大学者主页中积累了足够的情报网络. 我们的工作和这些平台相比有什么优势? 如果在本科阶段我可以很快回答,因为课程资料和创作的攻略在网络中具有 学校-specific 的唯一性, 但是在研究生阶段我不认为一些学术攻略是有独家性的,但是我觉得问题会转化为一个校友间的关系网络的构建, 这个平台可能是一个契机. 毕竟科研不止是一个人和导师的事情,能依靠的也不止同门. 平台能够囊括物理空间的校友,应该在某些切入点上会产生益处.

**Comment by EnixCoda** [comment]
本科和研究生的差异是我没有意识到的，我没读研 ~直接去接受社会的毒打了~

确实，存在这样的差异的话，对两者群体的吸引力需要由不同的内容提供。我之前光激动了，没看清这个仓库是针对研究生。我的经验和设计目的更贴近本科方面的需求。从你说的研究生的需求来看，我认为建论坛类型的网站可能是比较有效的方案。
- 论坛这类网站以留言为核心的设计便于相对清晰的交流
- 可以通过板块把不同的关注点的访问者分流，凭 GitHub issue 可能不好做到这一点
- 直接经营研究生的内容吸引流量比较困难的话，长远来看，通过设立校内生活之类的话题板块积累流量（包括本科生），有了总流量那更有希望慢慢转化，甚至能产生粘性，但这真的想远了……

以上思考没有很深，离开校园挺久了，给不了太具体的建议。我的老仓库就不要太仔细研究了，代码我自己都不好意思看哈哈哈，但如果需要技术方面的咨询的话我很乐意，可以随时联系我。

加油！

**Comment by tianyilt** [comment]
> 

没事没事,非常感谢学长的建议,等下次助教的时候忽悠几个本科生,让他们也建立一个(逃.

论坛是不错,不过如果学习资料都散布在各类帖子里面,可能后续来者就得到导航里面翻了,毕竟我们这个说是做课程共享攻略,但是实际上是以课程文件为主.   论坛的话等到给大家写博客的话会用到,我github这边主要工作可能就类似awesome list项目这样放很多链接,引导他们去论坛发言.

**Comment by oceanlvr** [comment]
黑暗森林可太真实了，花时间维护网站的同学确实不容易找。

**Comment by tianyilt** [comment]
问题不大，研究生其实没太大维护的内容，主要是提供一个空间帮大家分享自己的攻略
